# Generated by Django 5.1.2 on 2024-10-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_name', models.CharField(max_length=100)),
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
