# Generated by Django 5.1.2 on 2024-10-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_teacher_student_marks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='chemistry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='maths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='physics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
