# Generated by Django 5.1.2 on 2024-10-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_teacher_remove_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='marks',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
