# Generated by Django 5.1.2 on 2024-10-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_student_id_remove_student_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
