# Generated by Django 5.1.2 on 2024-10-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_student_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
