# Generated by Django 5.1.2 on 2024-10-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_student_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total',
        ),
    ]
