# Generated by Django 5.1.2 on 2024-10-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_student_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='percentage',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='student',
            name='total',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
