# Generated by Django 5.1.2 on 2024-10-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_student_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='performance',
            field=models.FloatField(default=0.0),
        ),
    ]
