# Generated by Django 5.1.2 on 2024-10-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_student_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_on',
        ),
    ]
