# Generated by Django 5.1.2 on 2024-10-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_student_created_on_remove_student_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='performance',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
