# Generated by Django 5.1.2 on 2024-10-24 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_student_created_on_student_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.teacher'),
        ),
    ]
