# Generated by Django 5.1.2 on 2024-10-24 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_student_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='student',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.teacher'),
        ),
    ]
