# Generated by Django 5.1.2 on 2024-10-24 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0003_department_hod_department_school_id'),
        ('School', '0001_initial'),
        ('myapp', '0023_remove_student_teacher_id_student_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Department.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='School.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
