# Generated by Django 5.1.2 on 2024-10-24 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0003_department_hod_department_school_id'),
        ('myapp', '0024_student_department_id_student_school_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Department.department'),
        ),
    ]
