# Generated by Django 5.1.2 on 2024-10-25 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_teacher_department_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school_id',
        ),
    ]
