# Generated by Django 5.1.2 on 2024-10-25 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0003_department_hod_department_school_id'),
        ('myapp', '0026_remove_student_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Department.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Department.department'),
        ),
    ]
