# Generated by Django 5.1.2 on 2024-10-28 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0003_school_is_active'),
        ('myapp', '0028_student_is_active_teacher_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='School.school'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='School.school'),
        ),
    ]
