# Generated by Django 5.1.2 on 2024-10-29 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_student_school_id_teacher_school_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='school_id',
        ),
    ]
