# Generated by Django 5.1.2 on 2024-10-29 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0003_school_is_active'),
        ('myapp', '0030_remove_teacher_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='School.school'),
        ),
    ]
