# Generated by Django 5.1.2 on 2024-11-04 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0007_remove_department_school_id'),
        ('School', '0004_school_departments'),
        ('myapp', '0031_teacher_school_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='chemistry',
        ),
        migrations.RemoveField(
            model_name='student',
            name='maths',
        ),
        migrations.RemoveField(
            model_name='student',
            name='physics',
        ),
        migrations.AlterField(
            model_name='student',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Department.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='School.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
