# Generated by Django 5.1.2 on 2024-11-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_student_percentage_alter_student_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='total',
            field=models.IntegerField(),
        ),
    ]
