# Generated by Django 5.1.2 on 2024-11-05 05:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Department', '0007_remove_department_school_id'),
        ('School', '0004_school_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(default='default_username', max_length=20, unique=True)),
                ('password', models.CharField(default='default_password', max_length=16, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('performance', models.FloatField(blank=True, editable=False, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Department.department')),
                ('school_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='School.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
