# Generated by Django 5.1.2 on 2024-11-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_custom_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='password',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
