# Generated by Django 5.1.2 on 2024-10-24 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0002_remove_department_hod'),
        ('School', '0001_initial'),
        ('myapp', '0022_alter_student_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.teacher'),
        ),
        migrations.AddField(
            model_name='department',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='School.school'),
        ),
    ]
