# Generated by Django 5.1.2 on 2024-10-30 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0005_department_is_active_alter_department_school_id'),
        ('myapp', '0031_teacher_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.teacher'),
        ),
    ]
