# Generated by Django 5.1.2 on 2024-10-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0006_alter_department_hod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='school_id',
        ),
    ]
